# Generated by Django 6.0.6 on 2026-06-19 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('NEW', 'New Passport'), ('RENEW', 'Renewal'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='NEW', max_length=10)),
                ('processing_type', models.CharField(choices=[('ORDINARY', 'Ordinary (PKR 5,000)'), ('URGENT', 'Urgent (PKR 10,000)')], default='ORDINARY', max_length=10)),
                ('pages', models.IntegerField(choices=[(36, '36 Pages'), (72, '72 Pages (+PKR 2,000)'), (100, '100 Pages (+PKR 4,000)')], default=36)),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('eye_color', models.CharField(blank=True, max_length=20)),
                ('identification_marks', models.TextField(blank=True)),
                ('cnic', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Invalid CNIC format')])),
                ('cnic_issue_date', models.DateField()),
                ('cnic_expiry_date', models.DateField()),
                ('family_registration_number', models.CharField(blank=True, max_length=20)),
                ('b_form_number', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_relationship', models.CharField(max_length=50)),
                ('highest_qualification', models.CharField(blank=True, max_length=100)),
                ('institute_name', models.CharField(blank=True, max_length=200)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('EMP', 'Employed'), ('UNEMP', 'Unemployed'), ('STU', 'Student')], default='UNEMP', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.CharField(blank=True, max_length=50)),
                ('travel_purpose', models.CharField(choices=[('TOURISM', 'Tourism'), ('STUDY', 'Study'), ('WORK', 'Work'), ('BUSINESS', 'Business'), ('RELIGIOUS', 'Religious')], default='TOURISM', max_length=50)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('expected_travel_date', models.DateField(blank=True, null=True)),
                ('previous_passport_number', models.CharField(blank=True, max_length=20)),
                ('fee', models.IntegerField(default=5000)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOC_VERIFIED', 'Documents Verified'), ('BIO_VERIFIED', 'Biometric Verified'), ('APPROVED', 'Approved'), ('PRINTING', 'Printing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='passport/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200)),
                ('father_cnic', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Invalid CNIC')])),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_contact', models.CharField(blank=True, max_length=15)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_cnic', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Invalid CNIC')])),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_contact', models.CharField(blank=True, max_length=15)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CNIC_FRONT', 'CNIC Front'), ('CNIC_BACK', 'CNIC Back'), ('PHOTO', 'Passport Size Photo'), ('BIRTH_CERT', 'Birth Certificate'), ('UTILITY_BILL', 'Utility Bill'), ('PREV_PASSPORT', 'Previous Passport Copy'), ('MARRIAGE_CERT', 'Marriage Certificate'), ('EDU_CERT', 'Educational Certificate')], max_length=20)),
                ('file', models.FileField(upload_to='passport/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passport/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='passport/signatures/')),
                ('left_thumb', models.ImageField(blank=True, null=True, upload_to='passport/fingerprints/')),
                ('right_thumb', models.ImageField(blank=True, null=True, upload_to='passport/fingerprints/')),
                ('verified', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_house', models.CharField(max_length=50)),
                ('perm_street', models.CharField(max_length=100)),
                ('perm_area', models.CharField(max_length=100)),
                ('perm_city', models.CharField(max_length=50)),
                ('perm_district', models.CharField(max_length=50)),
                ('perm_province', models.CharField(max_length=50)),
                ('perm_postal', models.CharField(max_length=10)),
                ('same_as_permanent', models.BooleanField(default=True)),
                ('curr_house', models.CharField(blank=True, max_length=50)),
                ('curr_street', models.CharField(blank=True, max_length=100)),
                ('curr_area', models.CharField(blank=True, max_length=100)),
                ('curr_city', models.CharField(blank=True, max_length=50)),
                ('curr_district', models.CharField(blank=True, max_length=50)),
                ('curr_province', models.CharField(blank=True, max_length=50)),
                ('curr_postal', models.CharField(blank=True, max_length=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(default='Simulated', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SpouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('spouse_cnic', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Invalid CNIC')])),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='passport.passportapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOC_VERIFIED', 'Documents Verified'), ('BIO_VERIFIED', 'Biometric Verified'), ('APPROVED', 'Approved'), ('PRINTING', 'Printing'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='passport.passportapplication')),
            ],
        ),
    ]
