# Generated by Django 6.0.6 on 2026-06-19 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CNICApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'CNIC must be 13 digits without dashes')])),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_cnic', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'CNIC must be 13 digits without dashes')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('domicile', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('cnic_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'CNIC must be 13 digits without dashes')])),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True)),
                ('same_as_permanent', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=50)),
                ('district_address', models.CharField(blank=True, max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('application_type', models.CharField(choices=[('NORMAL', 'Normal (PKR 700)'), ('URGENT', 'Urgent (PKR 2500)')], default='NORMAL', max_length=10)),
                ('fee', models.IntegerField(default=700)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cnic/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='cnic/signatures/')),
                ('left_thumb', models.ImageField(blank=True, null=True, upload_to='cnic/thumbs/')),
                ('right_thumb', models.ImageField(blank=True, null=True, upload_to='cnic/thumbs/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('generated_cnic', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='cnic/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
