# Generated by Django 6.0.6 on 2026-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0010_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='80FFF17FAB', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='469A03275ACA', max_length=20, unique=True),
        ),
    ]
