# Generated by Django 6.0.6 on 2026-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0020_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='250D9F93EF', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='ED5E4DAF1302', max_length=20, unique=True),
        ),
    ]
