# Generated by Django 6.0.6 on 2026-06-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0023_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='6DC61E8DFD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='C2918BE44478', max_length=20, unique=True),
        ),
    ]
