# Generated by Django 6.0.6 on 2026-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0025_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='2623BF1E87', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='84E4D5F6BCC8', max_length=20, unique=True),
        ),
    ]
