# Generated by Django 6.0.6 on 2026-06-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0028_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='challan',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='challan',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='challan_payments/'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='D8C03F5387', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='E08734D22788', max_length=20, unique=True),
        ),
    ]
