# Generated by Django 6.0.6 on 2026-06-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0029_bill_bill_image_challan_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='C697C9E114', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='55D4F149C348', max_length=20, unique=True),
        ),
    ]
