# Generated by Django 6.0.6 on 2026-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0031_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='A8C4AFE4E7', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='43AA0CDA0ECF', max_length=20, unique=True),
        ),
    ]
