# Generated by Django 6.0.6 on 2026-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0032_paymenttransaction_gateway_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='0196B319D9', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='194B12860937', max_length=20, unique=True),
        ),
    ]
