# Generated by Django 6.0.6 on 2026-06-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0033_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='0492F3FBB3', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='C95612238100', max_length=20, unique=True),
        ),
    ]
