# Generated by Django 6.0.6 on 2026-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0037_alter_challan_challan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='app_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='challan',
            name='challan_number',
            field=models.CharField(default='1245068A34', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('bill', 'Bill Payment'), ('challan', 'Challan Payment'), ('application', 'Application Fee')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='26E472C45EA8', max_length=20, unique=True),
        ),
    ]
